apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - image: "gcr.io/pde-apadhye/airflow:v1"
          name: airflow
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: airflow
          volumeMounts:
            - name: dags-storage
              mountPath: /usr/local/airflow/dags
            - name: tasks-storage
              mountPath: /usr/local/airflow/tasks
      volumes:
        - name: dags-storage
          persistentVolumeClaim:
            claimName: dags-pv-claim
        - name: tasks-storage
          persistentVolumeClaim:
            claimName: tasks-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi