version: 2

jobs:
  migrate_greenplum_test:
    docker:
      - image: boxfuse/flyway:4.2
    working_directory: ~/gpdb-airflow
    steps:
    - checkout

  run_tests:
    machine: true
    working_directory: ~/gpdb-airflow
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: |
          sudo apt-get update
          sudo apt-get install curl
          curl -sSL https://install.astronomer.io | sudo bash -s v0.7.5
    - run:
        name: Start Airflow
        command: |
          cd astro-airflow/ && astro airflow start && sleep 10

    - run:
        name: Create Gpdb connection
        command: |
          docker exec -it astroairflow_scheduler_1 airflow connections --delete --conn_id gpdb
          docker exec -it astroairflow_scheduler_1 airflow connections --add --conn_id gpdb \
          --conn_type postgres \
          --conn_host ${GPDB_HOST} \
          --conn_login ${GPDB_USER} \
          --conn_password ${GPDB_PASSWORD} \
          --conn_port ${GPDB_PORT} \
          --conn_schema ${GPDB_DATABASE}

    - run:
        name: Run Tests
        command: |
          docker exec -i astroairflow_scheduler_1 nosetests include/tests/

  migrate_greenplum_staging:
    docker:
    - image: boxfuse/flyway
    working_directory: ~/gpdb-airflow
    steps:
    - checkout

  deploy_airflow_staging:
    docker:
      - image: docker:18.09
    working_directory: ~/gpdb-airflow
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
#    - run:
#        name: Deploy to Airflow staging
#        command: |
#          docker login registry.${ASTRONOMER_BASE_DOMAIN} -u _ -p ${ASTRONOMER_SERVICE_ACCOUNT_KEY_STAGING}
#          docker build -t registry.${ASTRONOMER_BASE_DOMAIN}/${ASTRONOMER_RELEASE_NAME_STAGING}/airflow:ci-${CIRCLE_BUILD_NUM} ./pax-analytics
#          docker push registry.${ASTRONOMER_BASE_DOMAIN}/${ASTRONOMER_RELEASE_NAME_STAGING}/airflow:ci-${CIRCLE_BUILD_NUM}

  deploy_airflow_production:
    docker:
    - image: docker:18.09
    working_directory: ~/gpdb-airflow
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
#    - run:
#        name: Deploy to Airflow production
#        command: |
#          docker login registry.${ASTRONOMER_BASE_DOMAIN} -u _ -p ${ASTRONOMER_SERVICE_ACCOUNT_KEY_PRODUCTION}
#          docker build -t registry.${ASTRONOMER_BASE_DOMAIN}/${ASTRONOMER_RELEASE_NAME_PRODUCTION}/airflow:ci-${CIRCLE_BUILD_NUM} ./pax-analytics
#          docker push registry.${ASTRONOMER_BASE_DOMAIN}/${ASTRONOMER_RELEASE_NAME_PRODUCTION}/airflow:ci-${CIRCLE_BUILD_NUM}


workflows:
  version: 2
  build_and_deploy:
    jobs:
    - migrate_greenplum_test
    - run_test:
        requires:
        - migrate_greenplum_test
        filters:
          branches:
            only: master
    - migrate_greenplum_staging:
        requires:
        - run_test
        filters:
          branches:
            only: master
    - deploy_airflow_staging:
        requires:
        - migrate_greenplum_staging
        filters:
          branches:
            only: master
    - deploy_airflow_production_approval:
        type: approval
        requires:
        - deploy_airflow_staging
    - deploy_airflow_production:
        requires:
        - deploy_airflow_production_approval
        filters:
          branches:
            only: master
